#
# Copyright (C) 2024 nosignals
#
name: ULO Autobuilder

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'ulo'
        required: true
        default: 'ulo'
        type: string

jobs: 
  build_ipk:
    permissions:
      contents: write
    strategy:
      matrix:
        kernel: [5.4.265, 5.4.279, 6.6.6]
        devices: [s905x4]
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    steps:
      
      - name: Cleanup and Installing Prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get update
          sudo -E apt-get -y install lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
                    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Building OpenWrt
        run: |
          wget https://download946.mediafire.com/5v5oqbpisfhgz-18dOZft380r2BuBuWIUGtb0dB4NbfQRBr08CGNNLGSeXBzyIX7ubH6UwRvHW2lBEB1OzJHc1gkxhi7zLMPShFRVgqWDJqeexJh6eF5278l08bcwoWW7roe6dNtYdrd6z2c6RfvJ8i60UBsXd92Lx2hNKfSQ0sQaQ/30ghe4jqrh77gak/openwrt-23.05.4-armsr-armv8-generic-rootfs.tar.gz -P ./openwrt
          sudo ./ulo -k ${{ matrix.kernel }} -m ${{ matrix.devices }} -s 1024
          
      - name: Creating Package Artifact
        run: |
          mkdir -p ./artifact
          cp -rf ./out/${{ matrix.devices }}/* ./artifact/
          
      - name: Delivering Package
        uses: actions/upload-artifact@v2
        with:
          name: openwrt_package
          path: ./artifact/*

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/*
          tag: ${{ github.ref }}
          file_glob: true
          body: |
            ## OpenWRT AT01/AX810 Release
            Kernel :
            - 5.4.279 | Wifi On - Realtek
            - 5.4.265 | Wifi On - Unisoc
         
